config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :secret_keys
    
    namespace :v1 do
      get 'me' => 'me#show'
    end
  end
  root to: "accounts#index"
  resources :accounts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :api_secret_keys, class_name: "Api::SecretKey"
  has_many :live_keys, -> { live }, class_name: "Api::SecretKey"
  has_many :test_keys, -> { test }, class_name: "Api::SecretKey"

  validates :livemode, inclusion: { in: [true, false] }

  def name
    "Test account name"
  end

  def create_secret_key(mode: nil)
    mode ||= livemode? ? 'live' : 'test'
    api_secret_keys.create!(mode: mode)
  end

  def test!
    update!(livemode: false)
  end

  def live!
    update!(livemode: true)
  end
end

app/models/api/resources/account.rb
# frozen_string_literal: true

module Api
  module Resources
    class Account < Base
      required :id, Integer
      required :object, String
      # required :email, String
      required :name, String
      required :created, Integer
      required :updated_at, String
      required :metadata, Hash
      required :livemode, [TrueClass, FalseClass]
      optional :api_credentials, Array
      optional :api_credential, Hash
    end

    class ApiCredential < Base
      required :id, String
      required :object, String
      required :token, String
      required :created, Integer
      required :livemode, [TrueClass, FalseClass]
      required :metadata, Hash
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[ show edit update destroy ]

  # GET /accounts or /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1 or /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts or /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: "Account was successfully created." }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: "Account was successfully updated." }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    @account.destroy!

    respond_to do |format|
      format.html { redirect_to accounts_path, status: :see_other, notice: "Account was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.expect(account: [ :name ])
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_account.html.erb
<div id="<%= dom_id account %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= account.name %>
  </p>
</div>

app/views/accounts/_form.html.erb
<%= form_with(model: account, class: "contents") do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul class="list-disc ml-6">
        <% account.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": account.errors[:name].none?, "border-red-400 focus:outline-red-600": account.errors[:name].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<% content_for :title, "Editing account" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing account</h1>

  <%= render "form", account: @account %>

  <%= link_to "Show this account", @account, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to accounts", accounts_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/accounts/index.html.erb
<% content_for :title, "Accounts" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Accounts</h1>
    <%= link_to "New account", new_account_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="accounts" class="min-w-full">
    <% if @accounts.any? %>
      <% @accounts.each do |account| %>
        <%= render account %>
        <p>
          <%= link_to "Show this account", account, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
        </p>
      <% end %>
    <% else %>
      <p class="text-center my-10">No accounts found.</p>
    <% end %>
  </div>
</div>

app/views/accounts/new.html.erb
<% content_for :title, "New account" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New account</h1>

  <%= render "form", account: @account %>

  <%= link_to "Back to accounts", accounts_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/accounts/show.html.erb
<% content_for :title, "Showing account" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing account</h1>

  <%= render @account %>

  <%= link_to "Edit this account", edit_account_path(@account), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to accounts", accounts_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this account", @account, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium" %>
  </div>
</div>